# vim ft=yaml
# travis-ci.org definition

branches:
  only:
    - natsys/trunk

# non-container builds don't have enough RAM to reliably compile
sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
cache:
  - apt
  - ccache

env:
  matrix:
    - GCC_VERSION=5
    - GCC_VERSION=6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
# below requires https://github.com/travis-ci/apt-source-whitelist/pull/309
#      - llvm-toolchain-trusty-3.8
#      - llvm-toolchain-trusty-3.9
# llvm urls awaiting fix
# https://github.com/travis-ci/apt-source-whitelist/pull/288
# https://github.com/travis-ci/apt-source-whitelist/pull/309
    packages: # make sure these match debian/control contents
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6
      - bison
      - chrpath
      - cmake
      - debhelper
      - dh-apparmor
      - dpatch
      - gdb
      - libaio-dev
      - libboost-dev
      - libjudy-dev
      - libncurses5-dev
      - libpam0g-dev
      - libpcre3-dev
      - libreadline-gplv2-dev
      - libstemmer-dev
      - libssl-dev
      - libnuma-dev
      - libxml2-dev
      - lsb-release
      - perl
      - po-debconf
      - psmisc
      - zlib1g-dev
      - libcrack2-dev
      - libjemalloc-dev
      - devscripts # implicit for any build on Ubuntu
      - libtcmalloc-minimal4

env:
  - BUILD_TYPE=-DCMAKE_BUILD_TYPE=Debug -DWITH_JEMALLOC=yes -DSECURITY_HARDENED=no -DWITH_PIC=no -DCMAKE_CXX_FLAGS_DEBUG="-g -O0" -DCMAKE_C_FLAGS_DEBUG="-g -O0" "${TRAVIS_BUILD_DIR}"
  - BUILD_TYPE=-DCMAKE_BUILD_TYPE=Release -DWITH_JEMALLOC=yes -DSECURITY_HARDENED=yes -DCMAKE_CXX_FLAGS_RELEASE="-g" -DCMAKE_C_FLAGS_RELEASE="-g" "${TRAVIS_BUILD_DIR}"

# libsnappy-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3880
# liblzma-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3879
# libzmq-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3881
# libsystemd-daemon-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3882

script:
  - export MYSQL_BUILD_CC=/usr/bin/gcc-${GCC_VERSION} MYSQL_BUILD_CXX=/usr/bin/g++-${GCC_VERSION}
  - ${MYSQL_BUILD_CC} --version ; ${MYSQL_BUILD_CXX} --version
  - cd "${TRAVIS_BUILD_DIR}"
  - "LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 cmake -DWITH_INNOBASE_STORAGE_ENGINE=yes $BUILD_TYPE && LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 make -j $(grep -c processor /proc/cpuinfo) && cd ./mysql-test && ./mtr --suite=versioning --force --max-test-fail=0"
