# vim ft=yaml
# travis-ci.org definition

branches:
  only:
    - natsys/trunk

git:
  depth: 2

sudo: false
dist: trusty

language: cpp
compiler:
  - clang
cache:
  - apt
  - ccache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
# below requires https://github.com/travis-ci/apt-source-whitelist/pull/309
#      - llvm-toolchain-trusty-3.8
#      - llvm-toolchain-trusty-3.9
# llvm urls awaiting fix
# https://github.com/travis-ci/apt-source-whitelist/pull/288
# https://github.com/travis-ci/apt-source-whitelist/pull/309
    packages: # make sure these match debian/control contents
      - bison
      - chrpath
      - cmake
      - debhelper
      - dh-apparmor
      - dpatch
      - gdb
      - libaio-dev
      - libboost-dev
      - libjudy-dev
      - libncurses5-dev
      - libpam0g-dev
      - libpcre3-dev
      - libreadline-gplv2-dev
      - libstemmer-dev
      - libssl-dev
      - libnuma-dev
      - libxml2-dev
      - lsb-release
      - perl
      - po-debconf
      - psmisc
      - zlib1g-dev
      - libcrack2-dev
      - libjemalloc-dev
      - devscripts # implicit for any build on Ubuntu
      - valgrind

env:
  global:
    - RELEASE="-DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_JEMALLOC=yes -DSECURITY_HARDENED=yes"
  matrix:
    - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug -DWITH_JEMALLOC=yes" SUITES=versioning
    - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug" MTR_FLAGS="--valgrind --valgrind-option=--show-reachable=no --valgrind-option=--num-callers=120" SUITES=versioning
    - BUILD_TYPE=${RELEASE} SUITES=main,archive,optimizer_unfixed_bugs,parts,sys_vars,unit,vcol,innodb,innodb_gis,innodb_zip,innodb_fts
    - BUILD_TYPE=${RELEASE} SUITES=rpl
    - BUILD_TYPE=${RELEASE} SUITES=binlog,binlog_encryption,encryption,rocksdb,csv,federated,funcs_1,funcs_2,gcol,handler,heap,json,maria,percona,perfschema,plugins,multi_source,roles

# libsnappy-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3880
# liblzma-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3879
# libzmq-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3881
# libsystemd-daemon-dev # https://github.com/travis-ci/apt-package-whitelist/issues/3882

script:
  - ${CC} --version ; ${CXX} --version
  - export MTR_MEM=/tmp
  - cmake
     -DWITH_UNIT_TESTS=0
     -DWITH_UNITTEST=0
     -DWITH_INNOBASE_STORAGE_ENGINE=1
     -DWITHOUT_TOKUDB_STORAGE_ENGINE=1
     -DWITHOUT_ROCKSDB_STORAGE_ENGINE=1
     -DWITHOUT_MROONGA_STORAGE_ENGINE=1
     ${BUILD_TYPE}
  - make -j $(grep -c processor /proc/cpuinfo)
  - cd ./mysql-test
  - ./mtr ${MTR_FLAGS} -mem -pa=6 -force -max-test-fail=0 -suite=${SUITES} -skip-test-list='../skip_tests_travis'
